### ISSUE TITLE
undefined local variable or method 'store'

### ISSUE THREAD

**Issue by dapi** [rmustafin/russian_central_bank#11]
при update_state, возникает ошибка в russian_central_bank.rb:17

Версия 1.0.0

money - 6.5.0

**Comment by Saicheg** [comment]
описал в чем причина в #13

Если как у меня - 6.5, то я чтобы все работало - можно пока написать:

gem 'russian_central_bank', github: 'rubyroidlabs/russian_central_bank', branch: 'money-6.5-compatible'

**Comment by rmustafin** [comment]
Has to be fixed, the latest version depends on 6.7
Please keep in touch if it's not gone yet

@Saicheg you're in collaborators now, please feel free to maintain and fix that stuff. Thanks again, appreciate your help!
