### ISSUE TITLE
Error: 302 при обновлении курсов

### ISSUE THREAD

**Issue by unloved** [rmustafin/russian_central_bank#5]
wasabi-3.2.3/lib/wasabi/resolver.rb:44:in `load_from_remote'", wasabi-3.2.3/lib/wasabi/resolver.rb:32:in`resolve'", "wasabi-3.2.3/lib/wasabi/document.rb:141:in `xml'", "wasabi-3.2.3/lib/wasabi/document.rb:159:in`parse'", "wasabi-3.2.3/lib/wasabi/document.rb:146:in `parser'", "wasabi-3.2.3/lib/wasabi/document.rb:63:in`soap_actions'", "savon-2.3.3/lib/savon/operation.rb:21:in `ensure_exists!'", "savon-2.3.3/lib/savon/operation.rb:14:in`create'", "savon-2.3.3/lib/savon/client.rb:32:in `operation'", "savon-2.3.3/lib/savon/client.rb:36:in`call'", "russian_central_bank-0.2.1/lib/russian_central_bank.rb:46:in `exchange_rates'", "russian_central_bank-0.2.1/lib/russian_central_bank.rb:20:in`block in update_rates'", "russian_central_bank-0.2.1/lib/russian_central_bank.rb:19:in `synchronize'", "russian_central_bank-0.2.1/lib/russian_central_bank.rb:19:in`update_rates'"

russian_central_bank на wasabi, wasabi на savon, savon не переходит дальше при 302, а центробанк любит его отдавать

**Comment by pechorin** [comment]
+1 :( 

На самом деле делать такой фоллбек как-то жутковато. Особенно если курс является чем-то критичным :)

**Comment by Saicheg** [comment]
+1 тоже, при этом каждый раз когда запрашиваю

**Comment by pechorin** [comment]
@Saicheg, это сегодня началось :)

**Comment by Saicheg** [comment]
@pechorin неправда, уже 2 или 3 дня :)

**Comment by kirs** [comment]
(шутка про ЦБ и Рокетбанк)

**Comment by Saicheg** [comment]
(привет из Беларуси, привыкайте)

**Comment by pechorin** [comment]
@Saicheg, вообще эти 302-ые это уже "классика". У меня сегодня это просто началось очень активно. Я выгружаю курс каждые 5 минут, и вот сегодня до 5 вечера не смог выгрузить ни разу (sic!).

Пора видимо думать о внешних платных API.

**Comment by Saicheg** [comment]
@pechorin там уже все починили, если у тебя последняя версия money, то тебе:

```
gem 'russian_central_bank', github: 'kosmatov/russian_central_bank'
```

Если как у меня - 6.5, то я тут тоже починил:

```
gem 'russian_central_bank', github: 'rubyroidlabs/russian_central_bank', branch: 'money-6.5-compatible'
```
