### ISSUE TITLE
Ошибка при замене gem 'google_currency' на russian_central_bank

### ISSUE THREAD

**Issue by sadgb** [rmustafin/russian_central_bank#9]
При замене 
    Money.default_bank = Money::Bank::GoogleCurrency.new
на 
    Money.default_bank = Money::Bank::RussianCentralBank.new

Получаю следующую ошибку

Undefined method `/' for nil:NilClass
Extracted source (around line #242):

  def self.euro_rate
    Money.new(1_00, 'EUR').exchange_to(:RUB)
  end

/home/bets/.gems/ruby/2.1.0/bundler/gems/russian_central_bank-a2314ec89fd1/lib/russian_central_bank.rb:73:in `indirect_rate'
/home/bets/.gems/ruby/2.1.0/bundler/gems/russian_central_bank-a2314ec89fd1/lib/russian_central_bank.rb:47:in`get_rate'
money (6.5.1) lib/money/bank/variable_exchange.rb:92:in `exchange_with'
money (6.5.1) lib/money/money.rb:412:in`exchange_to'

**Comment by rmustafin** [comment]
Можешь скинуть свой Gemfile?
Есть подозрение, что исправлено в версии `1.0.0`
